### ISSUE TITLE
Make DSL installation optional

### ISSUE THREAD

**Issue by vanhoofmaarten** [isaaceindhoven/testcafe-scaffolding#2]
Make DSL installation optional

**Comment by RonaldvdH** [comment]
After a brief discussion, this is how we want to make DSL optional:
- Incorporate the question in the init script (Do you want to add [DSL](https://github.com/isaaceindhoven/testcafe-scaffolding/blob/master/docs/writing-the-testsuite.md)?
- Depending on this answer and the "Do you want to add example tests?" the example tests will be structured with or without DSL
- Update documentation to be able to link to a DSL section directly and explain why this might be useful for your project

**Comment by RonaldvdH** [comment]
After a new discussion following the work for this issue, we concluded that the current example tests don't need a DSL layer. This means they are very bad example tests that use a DSL layer.....

Things we should do now:
1. Refactor current example tests to not use DSL layer
2. Add a question in the init script "Do you want to add DSL https://github.com/isaaceindhoven/testcafe-scaffolding/blob/master/docs/writing-the-testsuite.md" When answer is "Yes" generate the DSL folder with a file which exports an empty class with `// Place your domain logic here`

Later we will think hard about what and how we want to incorporate more complex tests where using the DSL layer makes sense
